/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UdpViewer.java
 *
 * Created on Feb 16, 2009, 4:47:18 PM
 */

package jabezhelper;

/**
 *
 * @author Tom
 */
public class UdpViewer extends javax.swing.JPanel {

    /** Creates new form UdpViewer */
    public UdpViewer() {
        initComponents();
/*
             IPAddress myIpaddr = this.GetMyIpAddress();
            if (myIpaddr != null)
            {
                // start thread to listening on DxC UPD port
 //               udpTextBox1.StartLogging(myIpaddr, 5001);

                // start thread to listening on UCTA UPD port
                udpTextBox2.StartLogging(myIpaddr, 50880);
            }
 */
    }

/*
        public void StartLogging(IPAddress addr, int port)
        {
            // create a new socket connection
            endPoint = new IPEndPoint(addr, port);
            socket = new Socket(endPoint.Address.AddressFamily, SocketType.Dgram, ProtocolType.Udp);

            // start a new receving thread
            thread = new Thread(new ThreadStart(this.ReceiveData));
            thread.Start();
        }

        private void AddText(string text)
        {
            if (richTextBox1.InvokeRequired)
            {
                SetTextCallback d = new SetTextCallback(AddText);
                this.Invoke(d, new object[] { text });
            }
            else
            {
                richTextBox1.AppendText(text);
//                richTextBox1.SelectionStart = richTextBox1.TextLength;
//                richTextBox1.ScrollToCaret();
            }
        }

        public void ReceiveData()
        {
            try
            {
                // Creates an IPEndPoint to capture the identity of the sending host
                EndPoint senderRemote = (EndPoint)new IPEndPoint(IPAddress.Any, 0);
                socket.Bind(endPoint);

                byte[] data = new Byte[256];
                while (!closeRequested)
                {
                    // This call blocks
                    int recv = socket.ReceiveFrom(data, ref senderRemote);
                    AddText(DateTime.Now.ToString(" H:mm:ss:fff ") + Encoding.ASCII.GetString(data, 0, recv));
                }
            }
            catch (Exception err)
            {
                Console.WriteLine(err.ToString());
            }
        }

        public void CloseConnection()
        {
            closeRequested = true;
            socket.Close();
            thread.Abort();
        }

        private IPAddress GetMyIpAddress()
        {
            // Creates a socket for UDP datagram
            IPHostEntry host = Dns.GetHostEntry(Dns.GetHostName());
            foreach (IPAddress ipaddress in host.AddressList) {
//                AddText("\naddress found " + ipaddress.ToString());
                if (ipaddress.ToString().StartsWith("10.14"))
                {
                    return ipaddress;
                }
            }
            return null;
        }


 */


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
